---
title: "Conclusions and Discussion"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Overall, our multivariate analyses were very successful, with valid data and interesting results. In contrast to the perceived randomness of the tournament, we were able to deduce strong patterns according to expected trends, with higher seeds and better regular season teams performing better in the tournament (especially in the case of 1 seeds). Additionally, we saw a lot of Cinderella teams coming from 7, 10, and 11 seeds, who generally played difficult schedules in large conferences. In terms of variables, we saw that advanced offensive statistics like true shooting percentage and efficiency were generally the best predictors of success, reflecting the offensively-dominated modern game. Thus, while certainly not a silver bullet for predicting March Madness results, we were able to paint an illustrative picture of the tournament as a whole, encompassing the teams, the variables, the seeds, and the rounds.

## Factor Analysis
The factor analysis was relatively successful, with high suitability of our data and reasonably consistent and strong factors. The interpretations were relatively clear and illustrated interesting relationships among our indicators. Most notably, the results affirmed strong connections between overall regular season success and overall tournament success, continuing to undermine the narrative of fully random tournament results. While PCA suggested $5$ latent factors, we could have potentially tried only $3$ factors, as the interpretations for the final $2$ were much less clear and the correlations much weaker; however, the existence of the "aggression" factor and its negative correlation with tournament success was quite informative, making a case for these less prominent factors.

## Ordination
The ordination study was also quite successful, demonstrating clear and informative plots of our team groupings in two and three dimensions. Furthermore, we saw very strong correlations with our continuous team statistics, verifying their use as predictors and also the validity of our plots themselves. The most useful results probably came from the two-dimensional non-metric multidimensional scaling, which was slightly more linear and connected than the correspondence analysis results. The fitting of continuous variable contour plots only furthered this connection and demonstrated the heavy interactions between regular season statistics and tournament success. Thus, while not a direct modeling technique itself, ordination has allowed us to observe and analyze useful trends across several factors.

## Cluster Analysis
Continuing our pattern of success, the cluster analysis was also insightful, with each chosen technique providing interesting yet different results and conclusions. The most useful investigations probably came from the outlier distinction of single linkage hierarchial clustering, which was able to determine potential favorites, Cinderellas, etc., and from the k-means analysis including all of the teams. While these results are certainly not a conclusive solution to predicting every tournament, there are clear correlations between different types of teams, and the resulting clusters seem to have significant predictive ability.

# Points for Further Analysis
Despite the aforementioned success of our study, there is always room for improvement and further investigation. In fact, this is exactly what justifies further multivariate analysis of this data. Generally, the main desired improvement would be to find more unexpected results to explain more of the tournament randomness. This could probably be done by filtering out the "noise" of similar teams who did not perform well and maybe trying to use these techniques exclusively on the teams in question (Cinderellas, busts, etc.). Additionally, we may want to look at a larger pool of teams across more years, since it is almost always good to have more variables/data to look at. However, the chosen pool of data definitely had more than enough teams to deduce trends, and the recency of teams allows for pertinent observations like the dominance of offensive statistics. Nevertheless, doing further analysis with more data would only further illustrate these results, trends, and even differences across time.

## Factor Analysis
In terms of downsides, many of the latent factors could be deduced using basic logic, and applying factor analysis in this manner does not give us any insight into the individual teams and their sources of success (like cluster analysis does). In the future, it might be informative to try different (and probably smaller) subsets of variables to yield more detailed, unexpected conclusions in fewer latent factors. However, our results were not entirely expected and hence yielded some unique interpretations. Thus, factor analysis for this NCAAM basketball data was generally a success, and looking into some alternate approaches with this technique is definitely justified in the future.

## Ordination
Similar to the results of factor analysis, a lot of the observations were trivial, namely the fact that better statistics led to low seeds and higher tournament success. However, the specific groupings of seeds, namely for the Cinderella 7/11 seeds, along with the direction of the "snaking" effects, were actually very informative. In the future, it may be interesting to look at other specific subgroups, such as successful Cinderella teams or those who were upset early in the tournament. Furthermore, this is also definitely a technique that would benefit from even more years of data (yielding larger and more representative groups). Finally, we could potentially use this technique in conjunction with the results of cluster analysis to determine relationships between the clusters. Given the insights from this analysis, ordination is also a technique worth diving deeper into for NCAAM basketball data.

## Cluster Analysis
For cluster analysis, the main limitation came in the aforementioned "noise" within each group, as almost all of them included a relatively large amount of mediocrely performing teams that did not provide much predictive power. To solve this, we may want to look at a smaller set of teams that we are really interested in (namely those that performed surprisingly, either good or bad). Also, it may also be advantageous to look at different or larger groups in hierarchial clustering (namely with single linkage), as well as to analyze the statistical properties of each cluster. Finally, we could consider adding in notable teams from other years to see which group they would fall into and consequently gauge the predictive power of our clusters. In the end, however, this study was highly successful in establishing several core properties of cluster analysis on NCAAM basketball data and thus more than justified further work on the subject.